### ISSUE TITLE
Compression level

### ISSUE THREAD

**Issue by pakipaki2000** [johannesvollmer/lz4-compression-rs#1]
Hi,

i'd try your basic example but : 

```
    let uncompressed_data: &[u8] = b"Hello world, what's up?";

    let compressed_data = compression::compress(uncompressed_data);
    let decompressed_data = compression::decompress(&compressed_data).unwrap();

    assert_eq!(uncompressed_data, decompressed_data.as_slice());
```

But the size of compressed_data is 25, but uncompressed is 23?

Thanks for this crate :)

**Comment by johannesvollmer** [comment]
Hi,

Like many other compression algorithms, lz4 will add some information which describes _how exactly_ the bytes are compressed. Even if the information cannot be compressed too much, lz4 still needs that description among the compressed information. That way, we sometimes end up with more bytes than what we had started with. 

The more data we compress at once, the more space we save though. You can try to add more sentences to the `uncompressed_data` string and have a look at the size again :)

Keep in mind that I may be wrong though, I only forked this create and edited some bits to make it usable as a library, I am not an expert at lz4.

Have fun! :)

**Comment by pakipaki2000** [comment]
I see :)
Thanks for the clear explanation, I thought lz4 were made for small strings, i was wrong, do you know any solid algo for that? About 30-60 bytes data?

Thanks for the crate! Really easy to use

**Comment by johannesvollmer** [comment]
Glad I could help. I'm not aware of an compression algorithm that compresses that small data streams. Good luck with your search! :)
