### ISSUE TITLE
Not interoperable with the reference LZ4 implementation

### ISSUE THREAD

**Issue by Shnatsel** [johannesvollmer/lz4-compression-rs#5]
`lz4-compression` cannot decompress some files compressed with the reference LZ4 implementation through the `lz4` crate, it fails with the error `InvalidDeduplicationOffset` Likewise, the reference implementation cannot decode some of the files produced by `lz-compression`. See #4 for the reproduction steps.

However, `lz4-compression` can decompress the data it has compressed itself just fine. This is verified in #3.

This should be fixed, or alternatively the divergence in file format should be clearly advertised in the README.

**Comment by johannesvollmer** [comment]
Hi! Thanks for your efforts. I must go to bed now, that's why I can't merge your pull requests right now.  I'll do it on Saturday or Sunday though. Cheers!

**Comment by johannesvollmer** [comment]
I've updated the README as a quick fix and opened a new Issue for tracking the feature request, okay.?

**Comment by Shnatsel** [comment]
Sounds good to me. Thanks!
